matches:
  # Dates
  - trigger: ":date"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%Y/%m/%d"

  # Email
  - trigger: "@nolabel"
    replace: "-has:userlabels -in:sent -in:chat -in:draft -in:inbox"

  - trigger: "g@@"
    replace: "rares@getbetter.ro"

  - trigger: "e@@"
    replace: "rares.cosma@elastisys.com"

  - trigger: "o@@"
    replace: "oppy.fug@gmail.com"

  # Base64
  - trigger: ":be"
    replace: "{{res}}"
    vars:
      - name: "res"
        type: "shell"
        params:
          cmd: "xsel -bo | tr -d '\n' | base64 -w0"
  - trigger: ":bd"
    replace: "{{res}}"
    vars:
      - name: "res"
        type: "shell"
        params:
          cmd: "xsel -bo | tr -d '\n' | base64 -d"

  # Markdown
  - trigger: ":<>"
    replace: "[$|$]({{clip}})"
    vars:
      - name: "clip"
        type: "shell"
        params:
          cmd: "xsel -bo | tr -d '\n'"
  - trigger: ":img"
    replace: "![$|$]({{clip}})"
    vars:
      - name: "clip"
        type: "shell"
        params:
          cmd: "xsel -bo | tr -d '\n'"
  - trigger: ":wiki"
    replace: "{{res}}"
    vars:
      - name: "res"
        type: "shell"
        params:
          cmd: "xsel -bo | tr '\n' ' ' | xargs -0 findwiki"
  - trigger: ":imdb"
    replace: "{{res}}"
    vars:
      - name: "res"
        type: "shell"
        params:
          cmd: "xsel -bo | tr '\n' ' ' | xargs -0 findimdb"

  # Misc
  - trigger: ":uuid"
    replace: "{{res}}"
    vars:
      - name: "res"
        type: "shell"
        params:
          cmd: "uuidgen"
