#!/usr/bin/env bash

DOT=$( cd -P "$( dirname $(readlink -f "${BASH_SOURCE[0]}") )" && pwd )

source $DOT/lib.sh

xrandr --output $external --scale "${SCALE}x${SCALE}" --mode "${EW}x${EH}" \
	--fb "$(($IW + $EW_SCALED))x${EH_SCALED}" --pos "0x0" \
	--output $internal --off
