toggle_key: OFF

matches:
  # Dates
  - trigger: ":date"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%Y/%m/%d"

  # Email
  - trigger: "@nolabel"
    replace: "-has:userlabels -in:sent -in:chat -in:draft -in:inbox"

  - trigger: "g@"
    replace: "rares@getbetter.ro"

  # Markdown
  - trigger: ":a"
    replace: "[$|$]({{clip}})"
    vars:
      - name: "clip"
        type: "shell"
        params:
          cmd: "xsel -bo | tr -d '\n'"

  - trigger: ":img"
    replace: "![$|$]({{clip}})"
    vars:
      - name: "clip"
        type: "shell"
        params:
          cmd: "xsel -bo | tr -d '\n'"

  - trigger: ":wiki"
    replace: "{{res}}"
    vars:
      - name: "res"
        type: "shell"
        params:
          cmd: "xsel -bo | tr '\n' ' ' | xargs findwiki"

  # Misc
  - trigger: ":uuid"
    replace: "{{res}} foo"
    vars:
      - name: "res"
        type: "shell"
        params:
          cmd: "uuidgen"
