#!/bin/bash

BAT=$(acpi -b | grep -v "unavailable")
PERC=$(echo $BAT | grep -E -o '1?[0-9][0-9]?%')
DIS=$(echo $BAT | grep remaining)

if [[ -z "$BAT" ]]; then
    echo
    exit 0
fi

if [[ -z "$DIS" ]]; then
    STAT="⚡"
else
    if [ ${PERC%?} -le 20 ]; then
        STAT="🪫"
    else
        STAT="🔋"
    fi
fi

# Full and short texts
echo "$STAT $PERC"
echo "$STAT $PERC"

# Set urgent flag below 5% or use orange below 20%
[ ${PERC%?} -le 5 ] && {
    echo "#FF0000"
    exit 0
}
[ ${PERC%?} -le 20 ] && {
    echo "#FF8000"
    exit 0
}

exit 0
