#!/usr/bin/env bash

VPN_CONFIG=""
VPN_TYPE=""

# check openvpn
OVPN_PATH="/proc/sys/net/ipv4/conf/tun0"
if [[ -e "${OVPN_PATH}" ]]; then
  VPN_CONFIG=$(pgrep -a openvpn | head -1 | awk -F"/ovpn/" '{$0=$2}1' | cut -d/ -f1)
  VPN_TYPE="ovpn"
fi

# check wireguard
WG_DEV="$(find /proc/sys/net/ipv4/conf/wg0*)"
if ! test -z "$WG_DEV"; then
  VPN_CONFIG="$(printf $WG_DEV | awk -F"/wg0" '{$0=$2}1')"
  VPN_TYPE="wg"
fi

if ! test -z "$VPN_CONFIG"; then
  echo "🔐 VPN: ${VPN_CONFIG} (${VPN_TYPE})"
  echo "🔐 VPN: ${VPN_CONFIG} (${VPN_TYPE})"
  echo "#A8FF00"
  exit 0
else
  echo ""
fi
