#!/bin/bash

round() {
    n=$(printf "%.${1}g" "$2")
    if [ "$n" != "${n#*e}" ]
    then
        f="${n##*e-}"
        test "$n" = "$f" && f= || f=$(( ${f#0}+$1-1 ))
        printf "%0.${f}f" "$n"
    else
        printf "%s" "$n"
    fi
}

transfer=$(iwlist wlp58s0 rate | tail +2 | cut -d= -f2 | head -1)
unit=$(echo "$transfer" | cut -d' ' -f2)
mag=$(printf "%-3s" "$(round 2 "$(echo "$transfer" | cut -d' ' -f1)")")
echo -n "$mag $unit"
