daemonize = true
primary_threshold_ms = 5000
max_history = 200
synchronize_selection_with_clipboard = true
snippets = []

[log]
emit_journald = false
emit_stdout = true
emit_stderr = true
level = "INFO"

[watcher]
enable_clipboard = true
enable_primary = true
enable_secondary = false
filter_text_min_length = 1
filter_text_max_length = 20000000
denied_text_regex_patterns = []
capture_image = true
filter_image_max_size = 5242880

[grpc]
enable_http = true
enable_local_socket = true
host = "127.0.0.1"
port = 45045

[dbus]
enable = true

[metrics]
enable = false

[desktop_notification]
enable = false
