#!/usr/bin/env bash

DOT=$( cd -P "$( dirname $(readlink -f "${BASH_SOURCE[0]}") )" && pwd )

source $DOT/lib.sh

xrandr --output "$internal" --off \
  --output "$external" --auto \
  --scale "${SCALE}x${SCALE}" \
  --fb "${EW_SCALED}x${EH_SCALED}" \
  --panning "${EW_SCALED}x${EH_SCALED}"
