#!/usr/bin/env bash

VPN_CONFIG=""
VPN_TYPE=""

# check openvpn
OVPN_PATH="/proc/sys/net/ipv4/conf/tun0"
if [[ -e "${OVPN_PATH}" ]]; then
  vpn_configs=()
  vpn_types=()

  has_openvpn=$(pgrep -a openvpn | grep -oh -E 'daemon ([^ ]+)' | cut -d" " -f2)
  if [[ -n "${has_openvpn}" ]]; then
    vpn_configs+=("${has_openvpn}")
    vpn_types+=("ovpn")
  fi

  has_oc=$(pgrep -a openconnect | grep -oP 'https://\K[^\s]+')
  if [[ -n "${has_oc}" ]]; then
    vpn_configs+=("${has_oc}")
    vpn_types+=("oc")
  fi

  if [ ${#vpn_types[@]} -gt 0 ]; then
    configs=$(printf "%s + " "${vpn_configs[@]}"); configs=${configs%' + '}
    types=$(printf "%s + " "${vpn_types[@]}"); types=${types%' + '}
    echo "VPN: ${configs} (${types})"
  fi
  exit 0
fi

# check wireguard
WG_DEV="$(find /proc/sys/net/ipv4/conf/wg0* 2>/dev/null)"
if ! test -z "$WG_DEV"; then
  VPN_CONFIG="$(printf $WG_DEV | awk -F"/wg0" '{$0=$2}1')"
  VPN_TYPE=" (wg)"
  echo "VPN: ${VPN_CONFIG}${VPN_TYPE}"
  exit 0
fi

# check proton
PT_DEV="$(find /proc/sys/net/ipv4/conf/proton* 2>/dev/null)"
if ! test -z "$PT_DEV"; then
  VPN_CONFIG="proton"
  echo "VPN: ${VPN_CONFIG}"
  exit 0
fi
